/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TareasRouteImport } from './routes/tareas'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as PrescripcionRouteImport } from './routes/prescripcion'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacientesIdRouteImport } from './routes/pacientes_.$id'
import { Route as PTestsRouteImport } from './routes/p_.tests'
import { Route as PTareasRouteImport } from './routes/p_.tareas'
import { Route as PPerfilRouteImport } from './routes/p_.perfil'
import { Route as PLoginRouteImport } from './routes/p_.login'
import { Route as PInicioRouteImport } from './routes/p_.inicio'
import { Route as PDocumentosRouteImport } from './routes/p_.documentos'
import { Route as PCitasRouteImport } from './routes/p_.citas'
import { Route as DocumentosIdRouteImport } from './routes/documentos_.$id'
import { Route as PActivarTokenRouteImport } from './routes/p_.activar.$token'
import { Route as DocumentosPlantillaIdRouteImport } from './routes/documentos_.plantilla.$id'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescripcionRoute = PrescripcionRouteImport.update({
  id: '/prescripcion',
  path: '/prescripcion',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: '/pacientes_/$id',
  path: '/pacientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PTestsRoute = PTestsRouteImport.update({
  id: '/p_/tests',
  path: '/p/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const PTareasRoute = PTareasRouteImport.update({
  id: '/p_/tareas',
  path: '/p/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const PPerfilRoute = PPerfilRouteImport.update({
  id: '/p_/perfil',
  path: '/p/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PLoginRoute = PLoginRouteImport.update({
  id: '/p_/login',
  path: '/p/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PInicioRoute = PInicioRouteImport.update({
  id: '/p_/inicio',
  path: '/p/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const PDocumentosRoute = PDocumentosRouteImport.update({
  id: '/p_/documentos',
  path: '/p/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PCitasRoute = PCitasRouteImport.update({
  id: '/p_/citas',
  path: '/p/citas',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosIdRoute = DocumentosIdRouteImport.update({
  id: '/documentos_/$id',
  path: '/documentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PActivarTokenRoute = PActivarTokenRouteImport.update({
  id: '/p_/activar/$token',
  path: '/p/activar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosPlantillaIdRoute = DocumentosPlantillaIdRouteImport.update({
  id: '/documentos_/plantilla/$id',
  path: '/documentos/plantilla/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentos': typeof DocumentosRoute
  '/facturacion': typeof FacturacionRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/prescripcion': typeof PrescripcionRoute
  '/reportes': typeof ReportesRoute
  '/tareas': typeof TareasRoute
  '/tests': typeof TestsRoute
  '/documentos/$id': typeof DocumentosIdRoute
  '/p/citas': typeof PCitasRoute
  '/p/documentos': typeof PDocumentosRoute
  '/p/inicio': typeof PInicioRoute
  '/p/login': typeof PLoginRoute
  '/p/perfil': typeof PPerfilRoute
  '/p/tareas': typeof PTareasRoute
  '/p/tests': typeof PTestsRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/documentos/plantilla/$id': typeof DocumentosPlantillaIdRoute
  '/p/activar/$token': typeof PActivarTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentos': typeof DocumentosRoute
  '/facturacion': typeof FacturacionRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/prescripcion': typeof PrescripcionRoute
  '/reportes': typeof ReportesRoute
  '/tareas': typeof TareasRoute
  '/tests': typeof TestsRoute
  '/documentos/$id': typeof DocumentosIdRoute
  '/p/citas': typeof PCitasRoute
  '/p/documentos': typeof PDocumentosRoute
  '/p/inicio': typeof PInicioRoute
  '/p/login': typeof PLoginRoute
  '/p/perfil': typeof PPerfilRoute
  '/p/tareas': typeof PTareasRoute
  '/p/tests': typeof PTestsRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/documentos/plantilla/$id': typeof DocumentosPlantillaIdRoute
  '/p/activar/$token': typeof PActivarTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentos': typeof DocumentosRoute
  '/facturacion': typeof FacturacionRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/prescripcion': typeof PrescripcionRoute
  '/reportes': typeof ReportesRoute
  '/tareas': typeof TareasRoute
  '/tests': typeof TestsRoute
  '/documentos_/$id': typeof DocumentosIdRoute
  '/p_/citas': typeof PCitasRoute
  '/p_/documentos': typeof PDocumentosRoute
  '/p_/inicio': typeof PInicioRoute
  '/p_/login': typeof PLoginRoute
  '/p_/perfil': typeof PPerfilRoute
  '/p_/tareas': typeof PTareasRoute
  '/p_/tests': typeof PTestsRoute
  '/pacientes_/$id': typeof PacientesIdRoute
  '/documentos_/plantilla/$id': typeof DocumentosPlantillaIdRoute
  '/p_/activar/$token': typeof PActivarTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracion'
    | '/documentos'
    | '/facturacion'
    | '/historia'
    | '/login'
    | '/pacientes'
    | '/prescripcion'
    | '/reportes'
    | '/tareas'
    | '/tests'
    | '/documentos/$id'
    | '/p/citas'
    | '/p/documentos'
    | '/p/inicio'
    | '/p/login'
    | '/p/perfil'
    | '/p/tareas'
    | '/p/tests'
    | '/pacientes/$id'
    | '/documentos/plantilla/$id'
    | '/p/activar/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracion'
    | '/documentos'
    | '/facturacion'
    | '/historia'
    | '/login'
    | '/pacientes'
    | '/prescripcion'
    | '/reportes'
    | '/tareas'
    | '/tests'
    | '/documentos/$id'
    | '/p/citas'
    | '/p/documentos'
    | '/p/inicio'
    | '/p/login'
    | '/p/perfil'
    | '/p/tareas'
    | '/p/tests'
    | '/pacientes/$id'
    | '/documentos/plantilla/$id'
    | '/p/activar/$token'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracion'
    | '/documentos'
    | '/facturacion'
    | '/historia'
    | '/login'
    | '/pacientes'
    | '/prescripcion'
    | '/reportes'
    | '/tareas'
    | '/tests'
    | '/documentos_/$id'
    | '/p_/citas'
    | '/p_/documentos'
    | '/p_/inicio'
    | '/p_/login'
    | '/p_/perfil'
    | '/p_/tareas'
    | '/p_/tests'
    | '/pacientes_/$id'
    | '/documentos_/plantilla/$id'
    | '/p_/activar/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DocumentosRoute: typeof DocumentosRoute
  FacturacionRoute: typeof FacturacionRoute
  HistoriaRoute: typeof HistoriaRoute
  LoginRoute: typeof LoginRoute
  PacientesRoute: typeof PacientesRoute
  PrescripcionRoute: typeof PrescripcionRoute
  ReportesRoute: typeof ReportesRoute
  TareasRoute: typeof TareasRoute
  TestsRoute: typeof TestsRoute
  DocumentosIdRoute: typeof DocumentosIdRoute
  PCitasRoute: typeof PCitasRoute
  PDocumentosRoute: typeof PDocumentosRoute
  PInicioRoute: typeof PInicioRoute
  PLoginRoute: typeof PLoginRoute
  PPerfilRoute: typeof PPerfilRoute
  PTareasRoute: typeof PTareasRoute
  PTestsRoute: typeof PTestsRoute
  PacientesIdRoute: typeof PacientesIdRoute
  DocumentosPlantillaIdRoute: typeof DocumentosPlantillaIdRoute
  PActivarTokenRoute: typeof PActivarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescripcion': {
      id: '/prescripcion'
      path: '/prescripcion'
      fullPath: '/prescripcion'
      preLoaderRoute: typeof PrescripcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes_/$id': {
      id: '/pacientes_/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/tests': {
      id: '/p_/tests'
      path: '/p/tests'
      fullPath: '/p/tests'
      preLoaderRoute: typeof PTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/tareas': {
      id: '/p_/tareas'
      path: '/p/tareas'
      fullPath: '/p/tareas'
      preLoaderRoute: typeof PTareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/perfil': {
      id: '/p_/perfil'
      path: '/p/perfil'
      fullPath: '/p/perfil'
      preLoaderRoute: typeof PPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/login': {
      id: '/p_/login'
      path: '/p/login'
      fullPath: '/p/login'
      preLoaderRoute: typeof PLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/inicio': {
      id: '/p_/inicio'
      path: '/p/inicio'
      fullPath: '/p/inicio'
      preLoaderRoute: typeof PInicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/documentos': {
      id: '/p_/documentos'
      path: '/p/documentos'
      fullPath: '/p/documentos'
      preLoaderRoute: typeof PDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/citas': {
      id: '/p_/citas'
      path: '/p/citas'
      fullPath: '/p/citas'
      preLoaderRoute: typeof PCitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos_/$id': {
      id: '/documentos_/$id'
      path: '/documentos/$id'
      fullPath: '/documentos/$id'
      preLoaderRoute: typeof DocumentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/activar/$token': {
      id: '/p_/activar/$token'
      path: '/p/activar/$token'
      fullPath: '/p/activar/$token'
      preLoaderRoute: typeof PActivarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos_/plantilla/$id': {
      id: '/documentos_/plantilla/$id'
      path: '/documentos/plantilla/$id'
      fullPath: '/documentos/plantilla/$id'
      preLoaderRoute: typeof DocumentosPlantillaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DocumentosRoute: DocumentosRoute,
  FacturacionRoute: FacturacionRoute,
  HistoriaRoute: HistoriaRoute,
  LoginRoute: LoginRoute,
  PacientesRoute: PacientesRoute,
  PrescripcionRoute: PrescripcionRoute,
  ReportesRoute: ReportesRoute,
  TareasRoute: TareasRoute,
  TestsRoute: TestsRoute,
  DocumentosIdRoute: DocumentosIdRoute,
  PCitasRoute: PCitasRoute,
  PDocumentosRoute: PDocumentosRoute,
  PInicioRoute: PInicioRoute,
  PLoginRoute: PLoginRoute,
  PPerfilRoute: PPerfilRoute,
  PTareasRoute: PTareasRoute,
  PTestsRoute: PTestsRoute,
  PacientesIdRoute: PacientesIdRoute,
  DocumentosPlantillaIdRoute: DocumentosPlantillaIdRoute,
  PActivarTokenRoute: PActivarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
