/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as TareasRouteImport } from './routes/tareas'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RecibosRouteImport } from './routes/recibos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PrescripcionRouteImport } from './routes/prescripcion'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalAdminRouteImport } from './routes/legal-admin'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as HistoriaClinicaRouteImport } from './routes/historia-clinica'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformTestRequestsRouteImport } from './routes/platform_.test-requests'
import { Route as PlatformSolicitudesRouteImport } from './routes/platform_.solicitudes'
import { Route as PlatformReportesRouteImport } from './routes/platform_.reportes'
import { Route as PlatformAnunciosRouteImport } from './routes/platform_.anuncios'
import { Route as PacientesIdRouteImport } from './routes/pacientes_.$id'
import { Route as PTestsRouteImport } from './routes/p_.tests'
import { Route as PTareasRouteImport } from './routes/p_.tareas'
import { Route as PPerfilRouteImport } from './routes/p_.perfil'
import { Route as PLoginRouteImport } from './routes/p_.login'
import { Route as PInicioRouteImport } from './routes/p_.inicio'
import { Route as PDocumentosRouteImport } from './routes/p_.documentos'
import { Route as PCitasRouteImport } from './routes/p_.citas'
import { Route as LegalAdminAceptacionesRouteImport } from './routes/legal-admin_.aceptaciones'
import { Route as LegalAdminSlugRouteImport } from './routes/legal-admin_.$slug'
import { Route as FirmarTokenRouteImport } from './routes/firmar.$token'
import { Route as DocumentosIdRouteImport } from './routes/documentos_.$id'
import { Route as PFirmarDocIdRouteImport } from './routes/p_.firmar.$docId'
import { Route as PDocumentosIdRouteImport } from './routes/p_.documentos_.$id'
import { Route as PActivarTokenRouteImport } from './routes/p_.activar.$token'
import { Route as DocumentosPlantillaIdRouteImport } from './routes/documentos_.plantilla.$id'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecibosRoute = RecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescripcionRoute = PrescripcionRouteImport.update({
  id: '/prescripcion',
  path: '/prescripcion',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAdminRoute = LegalAdminRouteImport.update({
  id: '/legal-admin',
  path: '/legal-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaClinicaRoute = HistoriaClinicaRouteImport.update({
  id: '/historia-clinica',
  path: '/historia-clinica',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformTestRequestsRoute = PlatformTestRequestsRouteImport.update({
  id: '/platform_/test-requests',
  path: '/platform/test-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSolicitudesRoute = PlatformSolicitudesRouteImport.update({
  id: '/platform_/solicitudes',
  path: '/platform/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformReportesRoute = PlatformReportesRouteImport.update({
  id: '/platform_/reportes',
  path: '/platform/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAnunciosRoute = PlatformAnunciosRouteImport.update({
  id: '/platform_/anuncios',
  path: '/platform/anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: '/pacientes_/$id',
  path: '/pacientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PTestsRoute = PTestsRouteImport.update({
  id: '/p_/tests',
  path: '/p/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const PTareasRoute = PTareasRouteImport.update({
  id: '/p_/tareas',
  path: '/p/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const PPerfilRoute = PPerfilRouteImport.update({
  id: '/p_/perfil',
  path: '/p/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PLoginRoute = PLoginRouteImport.update({
  id: '/p_/login',
  path: '/p/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PInicioRoute = PInicioRouteImport.update({
  id: '/p_/inicio',
  path: '/p/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const PDocumentosRoute = PDocumentosRouteImport.update({
  id: '/p_/documentos',
  path: '/p/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PCitasRoute = PCitasRouteImport.update({
  id: '/p_/citas',
  path: '/p/citas',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAdminAceptacionesRoute = LegalAdminAceptacionesRouteImport.update({
  id: '/legal-admin_/aceptaciones',
  path: '/legal-admin/aceptaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAdminSlugRoute = LegalAdminSlugRouteImport.update({
  id: '/legal-admin_/$slug',
  path: '/legal-admin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmarTokenRoute = FirmarTokenRouteImport.update({
  id: '/firmar/$token',
  path: '/firmar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosIdRoute = DocumentosIdRouteImport.update({
  id: '/documentos_/$id',
  path: '/documentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PFirmarDocIdRoute = PFirmarDocIdRouteImport.update({
  id: '/p_/firmar/$docId',
  path: '/p/firmar/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const PDocumentosIdRoute = PDocumentosIdRouteImport.update({
  id: '/p_/documentos_/$id',
  path: '/p/documentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PActivarTokenRoute = PActivarTokenRouteImport.update({
  id: '/p_/activar/$token',
  path: '/p/activar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosPlantillaIdRoute = DocumentosPlantillaIdRouteImport.update({
  id: '/documentos_/plantilla/$id',
  path: '/documentos/plantilla/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentos': typeof DocumentosRoute
  '/facturacion': typeof FacturacionRoute
  '/historia': typeof HistoriaRoute
  '/historia-clinica': typeof HistoriaClinicaRoute
  '/inicio': typeof InicioRoute
  '/legal-admin': typeof LegalAdminRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/platform': typeof PlatformRoute
  '/prescripcion': typeof PrescripcionRoute
  '/privacidad': typeof PrivacidadRoute
  '/recibos': typeof RecibosRoute
  '/reportes': typeof ReportesRoute
  '/tareas': typeof TareasRoute
  '/terminos': typeof TerminosRoute
  '/tests': typeof TestsRoute
  '/documentos/$id': typeof DocumentosIdRoute
  '/firmar/$token': typeof FirmarTokenRoute
  '/legal-admin/$slug': typeof LegalAdminSlugRoute
  '/legal-admin/aceptaciones': typeof LegalAdminAceptacionesRoute
  '/p/citas': typeof PCitasRoute
  '/p/documentos': typeof PDocumentosRoute
  '/p/inicio': typeof PInicioRoute
  '/p/login': typeof PLoginRoute
  '/p/perfil': typeof PPerfilRoute
  '/p/tareas': typeof PTareasRoute
  '/p/tests': typeof PTestsRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/platform/anuncios': typeof PlatformAnunciosRoute
  '/platform/reportes': typeof PlatformReportesRoute
  '/platform/solicitudes': typeof PlatformSolicitudesRoute
  '/platform/test-requests': typeof PlatformTestRequestsRoute
  '/documentos/plantilla/$id': typeof DocumentosPlantillaIdRoute
  '/p/activar/$token': typeof PActivarTokenRoute
  '/p/documentos/$id': typeof PDocumentosIdRoute
  '/p/firmar/$docId': typeof PFirmarDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentos': typeof DocumentosRoute
  '/facturacion': typeof FacturacionRoute
  '/historia': typeof HistoriaRoute
  '/historia-clinica': typeof HistoriaClinicaRoute
  '/inicio': typeof InicioRoute
  '/legal-admin': typeof LegalAdminRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/platform': typeof PlatformRoute
  '/prescripcion': typeof PrescripcionRoute
  '/privacidad': typeof PrivacidadRoute
  '/recibos': typeof RecibosRoute
  '/reportes': typeof ReportesRoute
  '/tareas': typeof TareasRoute
  '/terminos': typeof TerminosRoute
  '/tests': typeof TestsRoute
  '/documentos/$id': typeof DocumentosIdRoute
  '/firmar/$token': typeof FirmarTokenRoute
  '/legal-admin/$slug': typeof LegalAdminSlugRoute
  '/legal-admin/aceptaciones': typeof LegalAdminAceptacionesRoute
  '/p/citas': typeof PCitasRoute
  '/p/documentos': typeof PDocumentosRoute
  '/p/inicio': typeof PInicioRoute
  '/p/login': typeof PLoginRoute
  '/p/perfil': typeof PPerfilRoute
  '/p/tareas': typeof PTareasRoute
  '/p/tests': typeof PTestsRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/platform/anuncios': typeof PlatformAnunciosRoute
  '/platform/reportes': typeof PlatformReportesRoute
  '/platform/solicitudes': typeof PlatformSolicitudesRoute
  '/platform/test-requests': typeof PlatformTestRequestsRoute
  '/documentos/plantilla/$id': typeof DocumentosPlantillaIdRoute
  '/p/activar/$token': typeof PActivarTokenRoute
  '/p/documentos/$id': typeof PDocumentosIdRoute
  '/p/firmar/$docId': typeof PFirmarDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentos': typeof DocumentosRoute
  '/facturacion': typeof FacturacionRoute
  '/historia': typeof HistoriaRoute
  '/historia-clinica': typeof HistoriaClinicaRoute
  '/inicio': typeof InicioRoute
  '/legal-admin': typeof LegalAdminRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/platform': typeof PlatformRoute
  '/prescripcion': typeof PrescripcionRoute
  '/privacidad': typeof PrivacidadRoute
  '/recibos': typeof RecibosRoute
  '/reportes': typeof ReportesRoute
  '/tareas': typeof TareasRoute
  '/terminos': typeof TerminosRoute
  '/tests': typeof TestsRoute
  '/documentos_/$id': typeof DocumentosIdRoute
  '/firmar/$token': typeof FirmarTokenRoute
  '/legal-admin_/$slug': typeof LegalAdminSlugRoute
  '/legal-admin_/aceptaciones': typeof LegalAdminAceptacionesRoute
  '/p_/citas': typeof PCitasRoute
  '/p_/documentos': typeof PDocumentosRoute
  '/p_/inicio': typeof PInicioRoute
  '/p_/login': typeof PLoginRoute
  '/p_/perfil': typeof PPerfilRoute
  '/p_/tareas': typeof PTareasRoute
  '/p_/tests': typeof PTestsRoute
  '/pacientes_/$id': typeof PacientesIdRoute
  '/platform_/anuncios': typeof PlatformAnunciosRoute
  '/platform_/reportes': typeof PlatformReportesRoute
  '/platform_/solicitudes': typeof PlatformSolicitudesRoute
  '/platform_/test-requests': typeof PlatformTestRequestsRoute
  '/documentos_/plantilla/$id': typeof DocumentosPlantillaIdRoute
  '/p_/activar/$token': typeof PActivarTokenRoute
  '/p_/documentos_/$id': typeof PDocumentosIdRoute
  '/p_/firmar/$docId': typeof PFirmarDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracion'
    | '/documentos'
    | '/facturacion'
    | '/historia'
    | '/historia-clinica'
    | '/inicio'
    | '/legal-admin'
    | '/login'
    | '/pacientes'
    | '/platform'
    | '/prescripcion'
    | '/privacidad'
    | '/recibos'
    | '/reportes'
    | '/tareas'
    | '/terminos'
    | '/tests'
    | '/documentos/$id'
    | '/firmar/$token'
    | '/legal-admin/$slug'
    | '/legal-admin/aceptaciones'
    | '/p/citas'
    | '/p/documentos'
    | '/p/inicio'
    | '/p/login'
    | '/p/perfil'
    | '/p/tareas'
    | '/p/tests'
    | '/pacientes/$id'
    | '/platform/anuncios'
    | '/platform/reportes'
    | '/platform/solicitudes'
    | '/platform/test-requests'
    | '/documentos/plantilla/$id'
    | '/p/activar/$token'
    | '/p/documentos/$id'
    | '/p/firmar/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracion'
    | '/documentos'
    | '/facturacion'
    | '/historia'
    | '/historia-clinica'
    | '/inicio'
    | '/legal-admin'
    | '/login'
    | '/pacientes'
    | '/platform'
    | '/prescripcion'
    | '/privacidad'
    | '/recibos'
    | '/reportes'
    | '/tareas'
    | '/terminos'
    | '/tests'
    | '/documentos/$id'
    | '/firmar/$token'
    | '/legal-admin/$slug'
    | '/legal-admin/aceptaciones'
    | '/p/citas'
    | '/p/documentos'
    | '/p/inicio'
    | '/p/login'
    | '/p/perfil'
    | '/p/tareas'
    | '/p/tests'
    | '/pacientes/$id'
    | '/platform/anuncios'
    | '/platform/reportes'
    | '/platform/solicitudes'
    | '/platform/test-requests'
    | '/documentos/plantilla/$id'
    | '/p/activar/$token'
    | '/p/documentos/$id'
    | '/p/firmar/$docId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracion'
    | '/documentos'
    | '/facturacion'
    | '/historia'
    | '/historia-clinica'
    | '/inicio'
    | '/legal-admin'
    | '/login'
    | '/pacientes'
    | '/platform'
    | '/prescripcion'
    | '/privacidad'
    | '/recibos'
    | '/reportes'
    | '/tareas'
    | '/terminos'
    | '/tests'
    | '/documentos_/$id'
    | '/firmar/$token'
    | '/legal-admin_/$slug'
    | '/legal-admin_/aceptaciones'
    | '/p_/citas'
    | '/p_/documentos'
    | '/p_/inicio'
    | '/p_/login'
    | '/p_/perfil'
    | '/p_/tareas'
    | '/p_/tests'
    | '/pacientes_/$id'
    | '/platform_/anuncios'
    | '/platform_/reportes'
    | '/platform_/solicitudes'
    | '/platform_/test-requests'
    | '/documentos_/plantilla/$id'
    | '/p_/activar/$token'
    | '/p_/documentos_/$id'
    | '/p_/firmar/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DocumentosRoute: typeof DocumentosRoute
  FacturacionRoute: typeof FacturacionRoute
  HistoriaRoute: typeof HistoriaRoute
  HistoriaClinicaRoute: typeof HistoriaClinicaRoute
  InicioRoute: typeof InicioRoute
  LegalAdminRoute: typeof LegalAdminRoute
  LoginRoute: typeof LoginRoute
  PacientesRoute: typeof PacientesRoute
  PlatformRoute: typeof PlatformRoute
  PrescripcionRoute: typeof PrescripcionRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RecibosRoute: typeof RecibosRoute
  ReportesRoute: typeof ReportesRoute
  TareasRoute: typeof TareasRoute
  TerminosRoute: typeof TerminosRoute
  TestsRoute: typeof TestsRoute
  DocumentosIdRoute: typeof DocumentosIdRoute
  FirmarTokenRoute: typeof FirmarTokenRoute
  LegalAdminSlugRoute: typeof LegalAdminSlugRoute
  LegalAdminAceptacionesRoute: typeof LegalAdminAceptacionesRoute
  PCitasRoute: typeof PCitasRoute
  PDocumentosRoute: typeof PDocumentosRoute
  PInicioRoute: typeof PInicioRoute
  PLoginRoute: typeof PLoginRoute
  PPerfilRoute: typeof PPerfilRoute
  PTareasRoute: typeof PTareasRoute
  PTestsRoute: typeof PTestsRoute
  PacientesIdRoute: typeof PacientesIdRoute
  PlatformAnunciosRoute: typeof PlatformAnunciosRoute
  PlatformReportesRoute: typeof PlatformReportesRoute
  PlatformSolicitudesRoute: typeof PlatformSolicitudesRoute
  PlatformTestRequestsRoute: typeof PlatformTestRequestsRoute
  DocumentosPlantillaIdRoute: typeof DocumentosPlantillaIdRoute
  PActivarTokenRoute: typeof PActivarTokenRoute
  PDocumentosIdRoute: typeof PDocumentosIdRoute
  PFirmarDocIdRoute: typeof PFirmarDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibos': {
      id: '/recibos'
      path: '/recibos'
      fullPath: '/recibos'
      preLoaderRoute: typeof RecibosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescripcion': {
      id: '/prescripcion'
      path: '/prescripcion'
      fullPath: '/prescripcion'
      preLoaderRoute: typeof PrescripcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-admin': {
      id: '/legal-admin'
      path: '/legal-admin'
      fullPath: '/legal-admin'
      preLoaderRoute: typeof LegalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia-clinica': {
      id: '/historia-clinica'
      path: '/historia-clinica'
      fullPath: '/historia-clinica'
      preLoaderRoute: typeof HistoriaClinicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_/test-requests': {
      id: '/platform_/test-requests'
      path: '/platform/test-requests'
      fullPath: '/platform/test-requests'
      preLoaderRoute: typeof PlatformTestRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_/solicitudes': {
      id: '/platform_/solicitudes'
      path: '/platform/solicitudes'
      fullPath: '/platform/solicitudes'
      preLoaderRoute: typeof PlatformSolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_/reportes': {
      id: '/platform_/reportes'
      path: '/platform/reportes'
      fullPath: '/platform/reportes'
      preLoaderRoute: typeof PlatformReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_/anuncios': {
      id: '/platform_/anuncios'
      path: '/platform/anuncios'
      fullPath: '/platform/anuncios'
      preLoaderRoute: typeof PlatformAnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes_/$id': {
      id: '/pacientes_/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/tests': {
      id: '/p_/tests'
      path: '/p/tests'
      fullPath: '/p/tests'
      preLoaderRoute: typeof PTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/tareas': {
      id: '/p_/tareas'
      path: '/p/tareas'
      fullPath: '/p/tareas'
      preLoaderRoute: typeof PTareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/perfil': {
      id: '/p_/perfil'
      path: '/p/perfil'
      fullPath: '/p/perfil'
      preLoaderRoute: typeof PPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/login': {
      id: '/p_/login'
      path: '/p/login'
      fullPath: '/p/login'
      preLoaderRoute: typeof PLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/inicio': {
      id: '/p_/inicio'
      path: '/p/inicio'
      fullPath: '/p/inicio'
      preLoaderRoute: typeof PInicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/documentos': {
      id: '/p_/documentos'
      path: '/p/documentos'
      fullPath: '/p/documentos'
      preLoaderRoute: typeof PDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/citas': {
      id: '/p_/citas'
      path: '/p/citas'
      fullPath: '/p/citas'
      preLoaderRoute: typeof PCitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-admin_/aceptaciones': {
      id: '/legal-admin_/aceptaciones'
      path: '/legal-admin/aceptaciones'
      fullPath: '/legal-admin/aceptaciones'
      preLoaderRoute: typeof LegalAdminAceptacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-admin_/$slug': {
      id: '/legal-admin_/$slug'
      path: '/legal-admin/$slug'
      fullPath: '/legal-admin/$slug'
      preLoaderRoute: typeof LegalAdminSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmar/$token': {
      id: '/firmar/$token'
      path: '/firmar/$token'
      fullPath: '/firmar/$token'
      preLoaderRoute: typeof FirmarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos_/$id': {
      id: '/documentos_/$id'
      path: '/documentos/$id'
      fullPath: '/documentos/$id'
      preLoaderRoute: typeof DocumentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/firmar/$docId': {
      id: '/p_/firmar/$docId'
      path: '/p/firmar/$docId'
      fullPath: '/p/firmar/$docId'
      preLoaderRoute: typeof PFirmarDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/documentos_/$id': {
      id: '/p_/documentos_/$id'
      path: '/p/documentos/$id'
      fullPath: '/p/documentos/$id'
      preLoaderRoute: typeof PDocumentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p_/activar/$token': {
      id: '/p_/activar/$token'
      path: '/p/activar/$token'
      fullPath: '/p/activar/$token'
      preLoaderRoute: typeof PActivarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos_/plantilla/$id': {
      id: '/documentos_/plantilla/$id'
      path: '/documentos/plantilla/$id'
      fullPath: '/documentos/plantilla/$id'
      preLoaderRoute: typeof DocumentosPlantillaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DocumentosRoute: DocumentosRoute,
  FacturacionRoute: FacturacionRoute,
  HistoriaRoute: HistoriaRoute,
  HistoriaClinicaRoute: HistoriaClinicaRoute,
  InicioRoute: InicioRoute,
  LegalAdminRoute: LegalAdminRoute,
  LoginRoute: LoginRoute,
  PacientesRoute: PacientesRoute,
  PlatformRoute: PlatformRoute,
  PrescripcionRoute: PrescripcionRoute,
  PrivacidadRoute: PrivacidadRoute,
  RecibosRoute: RecibosRoute,
  ReportesRoute: ReportesRoute,
  TareasRoute: TareasRoute,
  TerminosRoute: TerminosRoute,
  TestsRoute: TestsRoute,
  DocumentosIdRoute: DocumentosIdRoute,
  FirmarTokenRoute: FirmarTokenRoute,
  LegalAdminSlugRoute: LegalAdminSlugRoute,
  LegalAdminAceptacionesRoute: LegalAdminAceptacionesRoute,
  PCitasRoute: PCitasRoute,
  PDocumentosRoute: PDocumentosRoute,
  PInicioRoute: PInicioRoute,
  PLoginRoute: PLoginRoute,
  PPerfilRoute: PPerfilRoute,
  PTareasRoute: PTareasRoute,
  PTestsRoute: PTestsRoute,
  PacientesIdRoute: PacientesIdRoute,
  PlatformAnunciosRoute: PlatformAnunciosRoute,
  PlatformReportesRoute: PlatformReportesRoute,
  PlatformSolicitudesRoute: PlatformSolicitudesRoute,
  PlatformTestRequestsRoute: PlatformTestRequestsRoute,
  DocumentosPlantillaIdRoute: DocumentosPlantillaIdRoute,
  PActivarTokenRoute: PActivarTokenRoute,
  PDocumentosIdRoute: PDocumentosIdRoute,
  PFirmarDocIdRoute: PFirmarDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
